### ISSUE TITLE
npm build error 

### ISSUE THREAD

**Issue by worldquest** [SAP-samples/cloud-foundry-cap-azure-cities#15]
HI team,

I faced this CDS error. 

> city-explorer-demo-app@1.4.0 build:mta C:\My work\10. Azure solutions\SCPonAzure\open-service-broker-azure\contrib\cf\cloud-foundry-cap-azure-cities
> cds build/all && cds deploy && mbt build -p=cf --mtar=city-explorer-demo-app.mtar

'cds' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! city-explorer-demo-app@1.4.0 build:mta: `cds build/all && cds deploy && mbt build -p=cf --mtar=city-explorer-demo-app.mtar`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the city-explorer-demo-app@1.4.0 build:mta script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

PS C:\My work\10. Azure solutions\SCPonAzure\open-service-broker-azure\contrib\cf> cd cloud-foundry-cap-azure-cities
PS C:\My work\10. Azure solutions\SCPonAzure\open-service-broker-azure\contrib\cf\cloud-foundry-cap-azure-cities> npm install -g
npm WARN notsup Unsupported engine for city-explorer-demo-app@1.4.0: wanted: {"node":"^8.9"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: city-explorer-demo-app@1.4.0

=============================================================
do I need to lower down the npm / node version ?  any change rebuild with the latest npm version ? 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sap%2fcds - Not found
npm ERR! 404
npm ERR! 404  '@sap/cds@^3.20.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'city-explorer-demo-app'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by IObert** [comment]
Hi,

it sounds like you're missing an `npm install` before you run `npm run ...` 
I just saw that this is missing in the readme, I'll add it right now.

Thanks for pointing that out 👍
