### ISSUE TITLE
Error retrieving MTA: Could not find MTA mta_archives/${npm_package_name}_${npm_package_version}.mtar

### ISSUE THREAD

**Issue by worldquest** [SAP-samples/cloud-foundry-cap-azure-cities#16]
Hi Team, 

this time I follow again, I ended up the error. Any further idea ? 

 Azure solutions\SCPonAzure\samples\cloud-foundry-cap-azure-cities\.cloud-foundry-cap-azure-cities_mta_build_tmp\city-image-uploader" folder
[2020-04-25 00:26:52]  INFO finished building the "city-image-uploader" module
[2020-04-25 00:26:53]  INFO generating the metadata...
[2020-04-25 00:26:53]  INFO generating the MTA archive...
[2020-04-25 00:26:56]  INFO the MTA archive generated at: C:\My work\10. Azure solutions\SCPonAzure\samples\cloud-foundry-cap-azure-cities\mta_archives\city-explorer-demo-app.mtar
[2020-04-25 00:26:56]  INFO cleaning temporary files...
FAILED
Error retrieving MTA: Could not find MTA mta_archives/${npm_package_name}_${npm_package_version}.mtar
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! city-explorer-demo-app@1.4.0 deploy:cf: `npm run build:mta && cf deploy mta_archives/${npm_package_name}_${npm_package_version}.mtar`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the city-explorer-demo-app@1.4.0 deploy:cf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chanpark\AppData\Roaming\npm-cache\_logs\2020-04-24T16_27_03_000Z-debug.log

------------------------------------------------------------

silly lifecycle city-explorer-demo-app@1.4.0~deploy:cf: Args: [ '/d /s /c',
10 silly lifecycle   'npm run build:mta && cf deploy mta_archives/${npm_package_name}_${npm_package_version}.mtar' ]
11 silly lifecycle city-explorer-demo-app@1.4.0~deploy:cf: Returned: code: 1  signal: null
12 info lifecycle city-explorer-demo-app@1.4.0~deploy:cf: Failed to exec deploy:cf script
13 verbose stack Error: city-explorer-demo-app@1.4.0 deploy:cf: `npm run build:mta && cf deploy mta_archives/${npm_package_name}_${npm_package_version}.mtar`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid city-explorer-demo-app@1.4.0
15 verbose cwd C:\My work\10. Azure solutions\SCPonAzure\samples\cloud-foundry-cap-azure-cities
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy:cf"
18 verbose node v10.18.1
19 verbose npm  v6.13.4

**Comment by worldquest** [comment]
startCDS debug 

C:\Program Files\nodejs\npm.cmd run dev 
Debugger listening on ws://localhost:4014/0ba27f06-cc8f-4688-a409-4d8ce4ecf15c
For help, see: https://nodejs.org/en/docs/inspector
C:\My work\10. Azure solutions\SCPonAzure\cloud-foundry-cap-azure-cities\node_modules\.bin\cds:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! city-explorer-demo-app@1.4.0 dev: `node --inspect=localhost:4014 node_modules/.bin/cds run --in-memory`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the city-explorer-demo-app@1.4.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by worldquest** [comment]
Start Approuter 

'PORT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! city-image-uploader@1.0.0 dev: `PORT=4005 node --inspect=localhost:4015 app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the city-image-uploader@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

**Comment by IObert** [comment]
Hi,

I'd suggest focusing on the upper part of your first message. All the other error logs don't seem to be related to what you tried to do initially (`npm run deploy:cf` I assume)

It says it cannot find the file `mta_archives/${npm_package_name}_${npm_package_version}.mtar`. Can you check if there is such a file in `mta_archives`? The expressions in brackets are wild cards to the respective values in the `package.json`. They should have the values **city-explorer-demo-app** and **1.4.0** if you didn't change them

**Comment by worldquest** [comment]
HI 
yes. File is there.   does the file  needs to generate like  city-explorer-demo-app_1.4.0.mtar

chan@Azure:~/cap-azure-city/cloud-foundry-cap-azure-cities/mta_archives$ ls -la
total 95944
drwxr-xr-x  2 chan chan     4096 May  1 13:51 .
drwxr-xr-x 13 chan chan     4096 May  1 13:51 ..
-rw-r--r--  1 chan chan 98234852 May  1 13:51 city-explorer-demo-app.mtar
chan@Azure:~/cap-azure-city/cloud-foundry-cap-azure-cities/mta_archives$



[2020-05-01 13:51:19]  INFO finished building the "city-image-uploader" module
[2020-05-01 13:51:19]  INFO generating the metadata...
[2020-05-01 13:51:19]  INFO generating the MTA archive...
[2020-05-01 13:51:22]  INFO the MTA archive generated at: /home/chan/cap-azure-city/cloud-foundry-cap-azure-cities/mta_archives/city-explorer-demo-app.mtar
[2020-05-01 13:51:22]  INFO cleaning temporary files...
FAILED
Error retrieving MTA: Could not find MTA mta_archives/city-explorer-demo-app_1.4.0.mtar
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! city-explorer-demo-app@1.4.0 deploy:cf: `npm run build:mta && cf deploy mta_archives/${npm_package_name}_${npm_package_version}.mtar`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the city-explorer-demo-app@1.4.0 deploy:cf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chan/.npm/_logs/2020-05-01T13_51_25_703Z-debug.log

**Comment by worldquest** [comment]
don't know anyone did the workaround, i renamed cloud-foundry-cap-azure-cities/mta_archives/city-explorer-demo-app_1.4.0.mtar then build went to next step
